shop/urls.py
from django.contrib import admin
from django.urls import path
from shopapp import views,views_roznamcha,views_selling
from purchase import views_purchase
from products import views_vendor,views_product
from user_requests import request_views
from chat import views as views_chat
from chat import views_room
from user import views_login
# from qrapp import views_qr 
    
urlpatterns = [
    path('admin/shopapp/roznamcha/add/',views_roznamcha.roznamcha_form,name='roznamcha_form'), 
    path('roznamcha/save',views_roznamcha.roznamcha_save),
    path('admin/shopapp/selling/add/',views_selling.selling_form,name='selling_form'),
    path('selling/save',views_selling.selling_save),
    path('admin/purchase/purchase_bill/add/',views_purchase.purchase_bill_form,name="purchase_bill_form"),
    path('admin/purchase/purchase_bill/',views_purchase.purchase_show),
    path('purchase_bill/detail/<purchase_bill_id>/',views_purchase.purchase_show),
    path('products/<id>/',views_product.show,name='product_show'),
    path('products/select_service/<html_id>/',views_product.select_service,name='select_service'),
    path('vendors/<id>/',views_vendor.vendors_show,name='vendors_show'),
    path('chat/home/',views_chat.home),
    path('chat/send/',views_chat.send,name='send'),
    path('chat/getMessages/<room>/',views_chat.getMessage,name='get_message'),
    path('chat/room/<str:room_id>/',views_chat.room,name='room'),
    path('chat/checkview/',views_chat.checkview,name='checkview'),
    path('chat/get_rooms/',views_room.get_rooms,name='get_rooms'),
    # path('qrapp/qr_generater/',views_qr.qr_generater),
    # path('qrapp/qr_reader/',views_qr.qr_reader),
    path('requests_user/request/save/',request_views.request),
    path('admin/', admin.site.urls),
    path('',views.index),
    # path('/',views.index),
    path('host_to_heroku_login_form/',views_login.host_to_heroku_login_form,name='host_to_heroku_login_form'),
    path("host_to_heroku_login_form/submit/",views_login.host_to_heroku_submit,name="host_to_heroku_submit")
]
 

purchase/models.py
from email.policy import default
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from products.models import Product,Vendors
from shopapp.models import Customer

class Purchase_bill(models.Model):
    payment=models.IntegerField()
    purchasing_date=models.DateField()
    purchaser=models.ForeignKey(User,on_delete=models.DO_NOTHING,max_length=30)
    seller=models.ForeignKey(Vendors,on_delete=models.DO_NOTHING)
    discount=models.IntegerField(default=0)  
    total_purchase_bill=models.IntegerField()
    
    verbose_name_plural = "Purchasing Bill"
    
    def __str__(self):
        return f"{self.id}"
 

 
class Purchase_detail(models.Model):
    purchase_bill=models.ForeignKey(Purchase_bill,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.DO_NOTHING,null=False, blank=False)
    item_amount = models.IntegerField()
    item_price=models.IntegerField()
    return_qty=models.IntegerField(null=True,blank=True)      
    def __str__(self):
        return f"{self.id}"
    
    verbose_name_plural = "Purchase detail"

purchase/views.py
from django.shortcuts import render

# Create your views here.

templates/add_salary.html
<html>
    <head>
        <style>
            table{
                margin-left: auto;
                margin-right: auto;
            }
            .top_header{
                color:red;
                text-align: center;
            }

        </style>
    </head> 

<body>
    <form action="{{request.META.HTTP_NAME}}/users/salary/create/" method="post">
        {% csrf_token %}
    <table>
        <tr><h1 class="top_header">Add Users Salary</h1></tr>
        <tr>    
            <td>Account</td>
            <td><input type="text" name="account_no"></td>
        </tr>
        <tr>
            <td>Salary</td>
            <td><input type="text" name="salary"></td>
        </tr>
        <tr>
            <td><input type="submit" name="submit"></td>
        </tr>
    </table>
    </form>
</body>
</html>

templates/footer.html
<footer id="footer">
    <div class="footer-content" > This is@Compy right</div>
  </footer>

</body>
</html>

templates/hawala.html
<html>
    <head> 
        <style> 
            table{
                margin-left: auto;
                margin-right: auto;
            }
            .top_header{
                color:red;
                text-align: center;
            }

        </style>
    </head>

<body>
    <table>
        <tr><h1 class="top_header">Hawala</h1> </tr>
        <tr><a href="{{request.META.HTTP_NAME}}/bank_users/add/form">Add Hawala </a></tr>
        {% if rows %}
        <tr><th>Id</th><th>First Name</th><th>Last Name</th><th>Actions</th></tr>
        
        {% for hawala in hawalas %}
        <tr>
            <td>{{hawala.id}}</td>
            <td>{{hawala.sender}}</td>
            <td>{{hawala.status}}</td>
            <td><a href="{{request.META.HTTP_NAME}}/bank_users/delete/{{m.id}}">Delete </a>|<a href="{{request.META.HTTP_NAME}}/bank_users/update/form/{{m.id}}">Edit</a></td>
        </tr>
        {% endfor %}

        {% endif %}
     
    </table>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
</head>
<body style="background-color:black;">
  <header class="header" style="width: fit-content; align-items: center;height:3vh;">
    <a class="header--logo" href="#0">
      <img src="/static/assets/img/Tejaratistan Gold.svg" alt="Tejaratistan Gold">
      <!-- <p>Tejaratistan</p> -->
    </a>
    <!-- <button class="header--cta cta">Contact Us</button>
    <div class="header--nav-toggle">
      <span></span>
    </div> -->
  </header>
<div style="text-align:center;color:white;background-color:#d1c664;">
    <h2>Tejaratistan Chat</h2>
</div>


<div class="container" style="background-color:black;">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>




    <form id="post-form" method="POST" action="/chat/checkview/">
        {% csrf_token %}
        <label style="color:white;font-size:20px;">Room Name</label>
        <select type="text" name="room_name" id="room_name" width="100px" style="font-size:20px;" >
          {% for row in rooms %}
            <option>{{row.name}}</option>
          {% endfor %}
        </select>
        <label style="color:white;font-size:20px;">Username</label>
        <input type="text" name="username" id="username" width="100px" style="font-size:20px;"/>
        <input type="submit" value="Enter Room" style="font-size:20px;background-color: #d1c664; color:white;">
    </form>
</div>


</body>


</html>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
  function get_rooms(){
    url='/chat/get_rooms/';
    // fetch(url,{
    //   method:'GET',
    // }).then(response=>{
    //   response.json()
    // }).then(data=>{
    //   console.log("data=",data);
    // }).catch(error=>{console.log(error)});
    axios({
     method: "get",
     url: url,
    }).then(function (response) {
      room_name=document.getElementById("room_name");
      room_name.innerHTML="";
      for(key in response.data['rooms']){
        // console.log(response.data['rooms'][key]['name'])
        var option=document.createElement("option");
        option.text=response.data['rooms'][key]['name'];
        option.value=response.data['rooms'][key]['name'];
        // html="<option>"+response.data['rooms'][key]['name']+"</option>";
        room_name.appendChild(option);

      }
      // console.log(response.data['rooms']);
    });
    }

  get_rooms();
</script>

templates/master.html
<html>
    <head>
        <style>
        #footer {
            height: 50px; /* the footer's total height */
          }
          
          #footer-content {
            background-color: #f3e5f5;
            border: 1px solid #ab47bc;
            height: 32px; /* height + top/bottom paddding + top/bottom border must add up to footer height */
            padding: 8px;
          }
        </style>
    </head>
<body>

<h1>Welcome</h1>

{% block myheader%}
{% endblock %}

{% block mymessage %}
{% endblock %}



{% include 'footer.html'%}

templates/myfirst.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>

        <link rel="stylesheet" href="{% static 'myfirst.css' %}" />
        <style>
            h1{
                color:brown;
            }

            
        </style>
    </head>
<body>

<h1>Hello World!</h1>
<p>Welcome to my first Django project!</p>


</body>
</html>

templates/purchase_show.html
<html lang="en-us" dir="ltr">
    <head>
        <title>Add purchase_bill | Shirkat</title>
        <script src="/static/assets/js/purchase/purchase.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
        <!-- <script src="/static/admin/js/nav_sidebar.js" defer=""></script> -->
        <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
        <!-- <script src="/admin/jsi18n/"></script>
        <script src="/static/admin/js/vendor/jquery/jquery.js"></script>
        <script src="/static/admin/js/calendar.js"></script>
        <script src="/static/admin/js/jquery.init.js"></script>
        <script src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
        <script src="/static/admin/js/core.js"></script>
        <script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
        <script src="/static/admin/js/actions.js"></script>
        <script src="/static/admin/js/urlify.js"></script>
        <script src="/static/admin/js/prepopulate.js"></script>
        <script src="/static/admin/js/vendor/xregexp/xregexp.js"></script> -->
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    </head>

<body class=" app-shopapp model-purchase_bill change-form" data-admin-utc-offset="0">
<!-- Container -->
<div id="container"> 
    <!-- Header -->
    
    <div id="header">
        <div id="branding">
            <h1 id="site-name"><a href='/'><h1 style='color:rgb(255, 174, 0); font-weight:bold; text-align:center; font-size:40px'>Tejaratistan</h1></a></h1>
        </div>
 
        <div id="user-tools">
                Welcome,
                <strong>admin</strong>.
                    <a href="/">View site</a> /
                <a href="/admin/password_change/">Change password</a> /
                <a href="/admin/logout/">Log out</a>   
        </div>
    </div>
    
    <!-- END Header -->
        
    <div class="breadcrumbs">
    <a href="/admin/">Home</a>
    › <a href="/admin/purchase/">Shopapp</a>
    › <a href="/admin/purchase/purchase_bill/">Purchase_bills</a>
    › Add purchase_bill
    </div>

    <div class="main shifted" id="main"> 
        
        <div class="content">
            
            <!-- Content -->
            <div id="content" class="colM">   
                    

                <div id="content-main">
                            <div>
                                <fieldset class="module aligned ">    
                                    <table  id="table_form" style="margin-left:auto;margin-right:auto"> 
                                            <caption>
                                                <a href="/admin/shopapp/" class="section" title="Models in the Shopapp application">Shopapp</a>
                                            </caption>
                               
                                            <tbody>
                                                <tr>
                                                    
                                                    <th>
                                                        <label style="float:left"  >  Bill No</label>                      
                                                    </th>

                                                    <th>
                                                        <label style="float:left"  >  purchaser</label>                      
                                                    </th>
                                                    <th>
                                                         <label >seller</label>   
                                                    </th>
                                                    <th>
                                                          <label for="id_return_qty">total_bill</label>                     
                                                    </th>
                                                    <th>
                                                          <label>payment</label>           
                                                    </th>
                                                    <th>
                                                          <label for="id_return_qty">discount</label>                     
                                                    </th>
                                                    <th>
                                                        purchasing_date
                                                    </th>
                                                    <th>Actions</th>
                                                </tr>


                                                
                                                {%for row in purchase_bills %}
                                                <tr>
                                                    <td> 
                                                        {{row.id}}
                                                    </td> 
                                                    <td>
                                                        {{row.purchaser}}
                                                    </td>
                                                                                
                                                    <td>
                                                        {{row.seller}}
                                                    </td>       
                                                    <td>
                                                        {{row.total_purchase_bill}} 
                                                    </td>  
                                                    <td>
                                                      {{row.payment}}
                                                    </td>    
                                                    
                                                    <td>
                                                        {{row.discount}}
                                                    </td>

                                                    
                                                    <td>
                                                        {{row.purchasing_date}}
                                                    </td>

                                                    <td><a href="/purchase_bill/update/{{row.id}}/" class="btn btn-success" role="button" >update</a> | <a href="/purchase_bill/delete/{{row.id}}/" role="button" class="btn btn-success" >delete</a> | <a href="/purchase_bill/detail/{{row.id}}/" role="button" class="btn btn-info" >Detail</a></td>

                                                 </tr>
                                                {% endfor %}
                                                    
                                            </tbody>
                                  
                                    </table>
                                </fieldset>
                        </div>
                    </form>
                </div>  <!--end of div content-main-->
                    <br class="clear">
            </div>     <!--end of div colM-->
            <!-- END Content -->
            <div id="footer"></div>
        </div><!-- end of div content-->
    </div> <!--- end of div main shifted -->
</div><!-- end of div container -->
<!-- END Container -->



</div><!-- end of  calendarbox module div-->
</body>
</html>

<script>purchase_bills()</script>

templates/room.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
  height: 100vh;
}

.container {
  border: 2px solid lightslategray;
  background-color:white;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: lightgrey;
  background-color: white;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
<script   src="/static/assets/js/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
<script src="/static/assets/js/chat/chat.js">
</script>
</head>
<body style="background-color:black;">

<h2 style="text-align:center;background-color:#d1c664;color:white;">{{room_name}} - Tejaratistan</h2>

<div id="display_chat" style="height: 70vh; overflow: scroll;">

  <div class="container darker">
    <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
    <span class="time-left">20th, April 2021</span>
  </div>

</div>

<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

    <form id="post-form">
        {% csrf_token %}
        <input type="hidden" name="username" id="username" value="{{username}}"/>
        <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}"/>
        <!-- <input type="text" name="message" id="message" width="100px" /> -->
        <textarea name="message" id="message" col="" rows="4" cols="68" style="font-weight:bolder;font-size:20px"></textarea>
        <input type="submit" value="Send" style="font-size:20px;background-color: #d1c664; color:white;">
    </form>
</div>


</body>



<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/chat/send/',
      data:{
          username:$('#username').val(),
          room_id:$('#room_id').val(),
          message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>

</html>


<script>  
function get_messages(){
    //console.log("room_name=");
      url="/chat/getMessages/{{room_name}}/";
      //console.log(url)
      $.ajax({
          
          type: 'GET',
          url :url,
          success: function(response){
              //console.log("test "+response);
              //console.log("Objects.keys(response) ",Object.keys(response))
              $("#display_chat").empty();
              username=$("#username").val();
              
              for (var key in response.messages)
              {
                var messenger=response.messages[key].user;
                //console.log("username:",username," messenger response.messages[key].user:",response.messages[key].user," ==",response.messages[key].user==username)    
                  //console.log("response.messages[key].user=",response.messages[key].user)
                  if(messenger==username){
                    var temp="<div class='container darker' style='text-align:right;'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-right'>"+response.messages[key].date+"</span></div>";
                  }
                  else{
                    var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                  }
                  //var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                  $("#display_chat").append(temp);
              }
              scroll();
          },
          error: function(response){
              alert('An error occured')
          }
      });
  }

</script>

<script>

  document.addEventListener("DOMContentLoaded", function(event) {
      setInterval(get_messages,2000);
  });
  
  
  </script>
  

templates/roznamcha.html
<html>
    <head>
        <style>
            table{
                margin-left: auto;
                margin-right: auto;
            }
            .top_header{
                color:red;
                text-align: center;
            }

            input,select{
                padding:5%;
            }

            #danger{
                color:white;
                background-color:darkred;
            }
            
            #success{
                color:white;
                background-color:darkgreen;
            }
            

        </style>
    </head>

<body>

<div>   
     
    <table> 
        <tr> <td></td> </tr>   
    
        <tr>
        <td colspan=2>
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div id='danger' class='alert alert-danger'>
                
                {% else %}
                <div id='success' class='alert alert-success'>
                {%endif%}
                {{message}}
                </div>
            {% endfor %}
        </td>
         </tr>

      

        <form action="{{request.META.HTTP_NAME}}/roznamcha/save" method="post">
            {% csrf_token %}
            <tr><h1 class="top_header">Add Daily Roznamch</h1></tr>
        <tr>    
            <td>Spender</td>
            <td><select  name="spender" required> {% for user in users%} <option>{{user}}</option> {% endfor %} </select></td>
        </tr>
        <tr>
            <td>Spent Amount</td>
            <td><input type="text" name="total_spent" required></td>
        </tr>
         <tr>
            <td>Detail</td>
            <td><input type="text" name="detail" required></td>
        </tr>
        <tr>
            <td><input type="submit" value="save" name="submit" style="padding:8.7px"></td> <td><a href="{{request.META.HTTP_NAME}}/admin/shopapp/roznamcha/"><input type="button" value="Detail" ></a></td>
        </tr>
   
    </table>
    </form>
</div>
</body>
</html>

templates/salary.html
<html>
    <head>
        <style>
            table{
                margin-left: auto;
                margin-right: auto;
            }
            .top_header{
                color:red;
                text-align: center;
            }

        </style>
    </head>

<body>
    
    <table>
        <tr><h1 class="top_header"> Users Salary</h1></tr>
        <tr><th>Id</th><th>Account</th><th>Salary</th><th>Actions</th></tr>
       
        {% for sal in bank_salaries%}
        <tr>
        <td>{{sal.id}}</td>
        <td>{{sal.account_no}}</td>
        <td>{{sal.amount}}</td>
        <td><a href="{{request.META.HTTP_NAME}}/users/salary/edit/form/{{sal.id}}">Edit </a> <a href="{{request.META.HTTP_NAME}}/users/salary/delete/{{sal.id}}">Delete</a>  </td>
        </tr>
        {% endfor %}
        
    </table>
    <p>  <a href="{{request.META.HTTP_NAME}}/users/salary/form/">Add Salary </a>  </p>
  
</body>
</html>

templates/selling.html
<html>
    <head>
        <style>
            table{
                margin-left: auto;
                margin-right: auto;
            }
            .top_header{
                color:red;
                text-align: center;
            }

            input,select{
                padding:5%;
            }

        </style>
    </head>

<body>

<div>   
    
    <table>

        {% if messages %} 
        <tr>
        <td colspan=2>
            {% for message in messages %}
                {% if message.tag == 'error' %}
                    <span class="alert alert-danger">
                {% elif message.tag == 'success' %}
                    <span class="alert alert-success">
                {% endif %}
                    {{message}}
            {% endfor %}
         </td>
         </tr>
        {% endif %}
       
        <form action="{{request.META.HTTP_NAME}}/selling/save" method="post">
            {% csrf_token %}
            <tr><h1 class="top_header">Daily Selling </h1></tr>
        <tr>    
            <td>customer</td>
            <td><select  name="customer" required> {% for customer in customers %} <option>{{customer}}</option> {% endfor %} </select></td>
        </tr>
      
        <tr>    
            <td>Items</td>
            <td><select  name="item_name" required> {% for item in products %} <option>{{item}}</option> {% endfor %} </select></td>
        </tr>
        <tr>    
            <td>item price</td>
            <td><input type="number"  id="item_price" name="item_price" required> </td>
        </tr>
        <tr>
            <td>amount</td>
            <td><input type="number" id="amount" name="amount" required></td>
        </tr>
        <tr>
            <td>discount</td>
            <td><input type="number" id="discount" name="discount" ></td>
        </tr>
         <tr>
            <td>paid</td>
            <td><input type="number" id="paid" name="paid" required></td>
        </tr>
         <tr>
            <td>debit</td>
            <td><input type="number" id="debit" name="debit" ></td>
        </tr>

       
        <tr>
            <td><input type="submit" value="save" name="submit" style="padding:8.7px"></td> <td><a href="{{request.META.HTTP_NAME}}/admin/shopapp/roznamcha/"><input type="button" value="Detail" ></a></td>
        </tr>
   
    </table>
    </form>
</div> 
</body>
</html>

<script>



paid.addEventListener('change',(e)=>{
    var amount=document.getElementById("amount").value;
    console.log(amount);
    var item_price=document.getElementById("item_price").value;
    var discount=document.getElementById("discount").value;
    console.log(item_price)
    var total=amount*item_price-discount;
    var paid=document.getElementById("paid").value;
    document.getElementById("debit").value=total-paid;
    //alert(total);
    //console.log(total)
    debit=total-paid;
})
</script>